//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabicTranscriptionsMetro.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArabicTranscriptionsMetro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ب ähnelt.
        /// </summary>
        internal static string arabicBā {
            get {
                return ResourceManager.GetString("arabicBā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بُ ähnelt.
        /// </summary>
        internal static string arabicBāDamma {
            get {
                return ResourceManager.GetString("arabicBāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بٌ ähnelt.
        /// </summary>
        internal static string arabicBāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicBāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بَ ähnelt.
        /// </summary>
        internal static string arabicBāFatha {
            get {
                return ResourceManager.GetString("arabicBāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بً ähnelt.
        /// </summary>
        internal static string arabicBāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicBāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بِ ähnelt.
        /// </summary>
        internal static string arabicBāKasra {
            get {
                return ResourceManager.GetString("arabicBāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بٍ ähnelt.
        /// </summary>
        internal static string arabicBāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicBāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بْ ähnelt.
        /// </summary>
        internal static string arabicBāSukuun {
            get {
                return ResourceManager.GetString("arabicBāSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDāl {
            get {
                return ResourceManager.GetString("arabicDāl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎāl {
            get {
                return ResourceManager.GetString("arabicḎāl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālDamma {
            get {
                return ResourceManager.GetString("arabicDālDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎālDamma {
            get {
                return ResourceManager.GetString("arabicḎālDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālDammaTanwin {
            get {
                return ResourceManager.GetString("arabicDālDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎālDammaTanwin {
            get {
                return ResourceManager.GetString("arabicḎālDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālFatha {
            get {
                return ResourceManager.GetString("arabicDālFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎālFatha {
            get {
                return ResourceManager.GetString("arabicḎālFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālFathaTanwin {
            get {
                return ResourceManager.GetString("arabicDālFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎālFathaTanwin {
            get {
                return ResourceManager.GetString("arabicḎālFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālKasra {
            get {
                return ResourceManager.GetString("arabicDālKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎālKasra {
            get {
                return ResourceManager.GetString("arabicḎālKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālKasraTanwin {
            get {
                return ResourceManager.GetString("arabicDālKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎālKasraTanwin {
            get {
                return ResourceManager.GetString("arabicḎālKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālSukuun {
            get {
                return ResourceManager.GetString("arabicDālSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḎālSukuun {
            get {
                return ResourceManager.GetString("arabicḎālSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٨ ähnelt.
        /// </summary>
        internal static string arabicEight {
            get {
                return ResourceManager.GetString("arabicEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٥ ähnelt.
        /// </summary>
        internal static string arabicFive {
            get {
                return ResourceManager.GetString("arabicFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٤ ähnelt.
        /// </summary>
        internal static string arabicFour {
            get {
                return ResourceManager.GetString("arabicFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīm {
            get {
                return ResourceManager.GetString("arabicǦīm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīmDamma {
            get {
                return ResourceManager.GetString("arabicǦīmDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīmDammaTanwin {
            get {
                return ResourceManager.GetString("arabicǦīmDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīmFatha {
            get {
                return ResourceManager.GetString("arabicǦīmFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīmFathaTanwin {
            get {
                return ResourceManager.GetString("arabicǦīmFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīmKasra {
            get {
                return ResourceManager.GetString("arabicǦīmKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīmKasraTanwin {
            get {
                return ResourceManager.GetString("arabicǦīmKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicǦīmSukuun {
            get {
                return ResourceManager.GetString("arabicǦīmSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤā {
            get {
                return ResourceManager.GetString("arabicḤā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪā {
            get {
                return ResourceManager.GetString("arabicḪā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāDamma {
            get {
                return ResourceManager.GetString("arabicḤāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāDamma {
            get {
                return ResourceManager.GetString("arabicḪāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicḤāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicḪāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāFatha {
            get {
                return ResourceManager.GetString("arabicḤāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāFatha {
            get {
                return ResourceManager.GetString("arabicḪāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicḤāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicḪāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāKasra {
            get {
                return ResourceManager.GetString("arabicḤāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāKasra {
            get {
                return ResourceManager.GetString("arabicḪāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicḤāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicḪāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāSukuum {
            get {
                return ResourceManager.GetString("arabicḤāSukuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāSukuun {
            get {
                return ResourceManager.GetString("arabicḪāSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٩ ähnelt.
        /// </summary>
        internal static string arabicNine {
            get {
                return ResourceManager.GetString("arabicNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ١ ähnelt.
        /// </summary>
        internal static string arabicOne {
            get {
                return ResourceManager.GetString("arabicOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRā {
            get {
                return ResourceManager.GetString("arabicRā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRāDamma {
            get {
                return ResourceManager.GetString("arabicRāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicRāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRāFatha {
            get {
                return ResourceManager.GetString("arabicRāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicRāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRāKasra {
            get {
                return ResourceManager.GetString("arabicRāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicRāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicRāSukuun {
            get {
                return ResourceManager.GetString("arabicRāSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٧ ähnelt.
        /// </summary>
        internal static string arabicSeven {
            get {
                return ResourceManager.GetString("arabicSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīn {
            get {
                return ResourceManager.GetString("arabicSīn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīnDamma {
            get {
                return ResourceManager.GetString("arabicSīnDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīnDammaTanwin {
            get {
                return ResourceManager.GetString("arabicSīnDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīnFatha {
            get {
                return ResourceManager.GetString("arabicSīnFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīnFathaTanwin {
            get {
                return ResourceManager.GetString("arabicSīnFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīnKasra {
            get {
                return ResourceManager.GetString("arabicSīnKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīnKasraTanwin {
            get {
                return ResourceManager.GetString("arabicSīnKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicSīnSukuun {
            get {
                return ResourceManager.GetString("arabicSīnSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٦ ähnelt.
        /// </summary>
        internal static string arabicSix {
            get {
                return ResourceManager.GetString("arabicSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ت ähnelt.
        /// </summary>
        internal static string arabicTā {
            get {
                return ResourceManager.GetString("arabicTā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ث ähnelt.
        /// </summary>
        internal static string arabicṮā {
            get {
                return ResourceManager.GetString("arabicṮā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تُ ähnelt.
        /// </summary>
        internal static string arabicTāDamma {
            get {
                return ResourceManager.GetString("arabicTāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثُ ähnelt.
        /// </summary>
        internal static string arabicṮāDamma {
            get {
                return ResourceManager.GetString("arabicṮāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تٌ ähnelt.
        /// </summary>
        internal static string arabicTāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicTāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثٌ ähnelt.
        /// </summary>
        internal static string arabicṮāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicṮāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تَ ähnelt.
        /// </summary>
        internal static string arabicTāFatha {
            get {
                return ResourceManager.GetString("arabicTāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثَ ähnelt.
        /// </summary>
        internal static string arabicṮāFatha {
            get {
                return ResourceManager.GetString("arabicṮāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تً ähnelt.
        /// </summary>
        internal static string arabicTāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicTāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثً ähnelt.
        /// </summary>
        internal static string arabicṮāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicṮāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تِ ähnelt.
        /// </summary>
        internal static string arabicTāKasra {
            get {
                return ResourceManager.GetString("arabicTāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثِ ähnelt.
        /// </summary>
        internal static string arabicṮāKasra {
            get {
                return ResourceManager.GetString("arabicṮāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تٍ ähnelt.
        /// </summary>
        internal static string arabicTāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicTāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثٍ ähnelt.
        /// </summary>
        internal static string arabicṮāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicṮāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تْ ähnelt.
        /// </summary>
        internal static string arabicTāSukuun {
            get {
                return ResourceManager.GetString("arabicTāSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثْ ähnelt.
        /// </summary>
        internal static string arabicṮāSukuun {
            get {
                return ResourceManager.GetString("arabicṮāSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٣ ähnelt.
        /// </summary>
        internal static string arabicThree {
            get {
                return ResourceManager.GetString("arabicThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٢ ähnelt.
        /// </summary>
        internal static string arabicTwo {
            get {
                return ResourceManager.GetString("arabicTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZā {
            get {
                return ResourceManager.GetString("arabicZā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZāDamma {
            get {
                return ResourceManager.GetString("arabicZāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicZāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZāFatha {
            get {
                return ResourceManager.GetString("arabicZāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicZāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZāKasra {
            get {
                return ResourceManager.GetString("arabicZāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicZāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicZāSukuun {
            get {
                return ResourceManager.GetString("arabicZāSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٠ ähnelt.
        /// </summary>
        internal static string arabicZero {
            get {
                return ResourceManager.GetString("arabicZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die    ähnelt.
        /// </summary>
        internal static string doubleSpace {
            get {
                return ResourceManager.GetString("doubleSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 8 ähnelt.
        /// </summary>
        internal static string latinEight {
            get {
                return ResourceManager.GetString("latinEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5 ähnelt.
        /// </summary>
        internal static string latinFive {
            get {
                return ResourceManager.GetString("latinFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4 ähnelt.
        /// </summary>
        internal static string latinFour {
            get {
                return ResourceManager.GetString("latinFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 9 ähnelt.
        /// </summary>
        internal static string latinNine {
            get {
                return ResourceManager.GetString("latinNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        internal static string latinOne {
            get {
                return ResourceManager.GetString("latinOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 7 ähnelt.
        /// </summary>
        internal static string latinSeven {
            get {
                return ResourceManager.GetString("latinSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 6 ähnelt.
        /// </summary>
        internal static string latinSix {
            get {
                return ResourceManager.GetString("latinSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 ähnelt.
        /// </summary>
        internal static string latinThree {
            get {
                return ResourceManager.GetString("latinThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 ähnelt.
        /// </summary>
        internal static string latinTwo {
            get {
                return ResourceManager.GetString("latinTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        internal static string latinZero {
            get {
                return ResourceManager.GetString("latinZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   ähnelt.
        /// </summary>
        internal static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
    }
}
