//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabicTranscriptionsMetro.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArabicTranscriptionsMetro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ب ähnelt.
        /// </summary>
        internal static string arabicBa {
            get {
                return ResourceManager.GetString("arabicBa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بُ ähnelt.
        /// </summary>
        internal static string arabicBaDamma {
            get {
                return ResourceManager.GetString("arabicBaDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بٌ ähnelt.
        /// </summary>
        internal static string arabicBaDammaTanwin {
            get {
                return ResourceManager.GetString("arabicBaDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بَ ähnelt.
        /// </summary>
        internal static string arabicBaFatha {
            get {
                return ResourceManager.GetString("arabicBaFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بً ähnelt.
        /// </summary>
        internal static string arabicBaFathaTanwin {
            get {
                return ResourceManager.GetString("arabicBaFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بِ ähnelt.
        /// </summary>
        internal static string arabicBaKasra {
            get {
                return ResourceManager.GetString("arabicBaKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بٍ ähnelt.
        /// </summary>
        internal static string arabicBaKasraTanwin {
            get {
                return ResourceManager.GetString("arabicBaKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بْ ähnelt.
        /// </summary>
        internal static string arabicBaSukuun {
            get {
                return ResourceManager.GetString("arabicBaSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDāl {
            get {
                return ResourceManager.GetString("arabicDāl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālDamma {
            get {
                return ResourceManager.GetString("arabicDālDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālDammaSukuun {
            get {
                return ResourceManager.GetString("arabicDālDammaSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālFatha {
            get {
                return ResourceManager.GetString("arabicDālFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālFathaSukuun {
            get {
                return ResourceManager.GetString("arabicDālFathaSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālKasra {
            get {
                return ResourceManager.GetString("arabicDālKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālKasraSukuun {
            get {
                return ResourceManager.GetString("arabicDālKasraSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDālSukuun {
            get {
                return ResourceManager.GetString("arabicDālSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschim {
            get {
                return ResourceManager.GetString("arabicDschim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschimDamma {
            get {
                return ResourceManager.GetString("arabicDschimDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschimDammaTanwin {
            get {
                return ResourceManager.GetString("arabicDschimDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschimFatha {
            get {
                return ResourceManager.GetString("arabicDschimFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschimFathaTanwin {
            get {
                return ResourceManager.GetString("arabicDschimFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschimKasra {
            get {
                return ResourceManager.GetString("arabicDschimKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschimKasraTanwin {
            get {
                return ResourceManager.GetString("arabicDschimKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicDschimSukuun {
            get {
                return ResourceManager.GetString("arabicDschimSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٨ ähnelt.
        /// </summary>
        internal static string arabicEight {
            get {
                return ResourceManager.GetString("arabicEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٥ ähnelt.
        /// </summary>
        internal static string arabicFive {
            get {
                return ResourceManager.GetString("arabicFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٤ ähnelt.
        /// </summary>
        internal static string arabicFour {
            get {
                return ResourceManager.GetString("arabicFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤā {
            get {
                return ResourceManager.GetString("arabicḤā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪā {
            get {
                return ResourceManager.GetString("arabicḪā", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāDamma {
            get {
                return ResourceManager.GetString("arabicḤāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāDamma {
            get {
                return ResourceManager.GetString("arabicḪāDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāDammaSukuun {
            get {
                return ResourceManager.GetString("arabicḪāDammaSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāDammaTanwin {
            get {
                return ResourceManager.GetString("arabicḤāDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāFatha {
            get {
                return ResourceManager.GetString("arabicḤāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāFatha {
            get {
                return ResourceManager.GetString("arabicḪāFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāFathaSukuum {
            get {
                return ResourceManager.GetString("arabicḪāFathaSukuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāFathaTanwin {
            get {
                return ResourceManager.GetString("arabicḤāFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāKasra {
            get {
                return ResourceManager.GetString("arabicḤāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāKasra {
            get {
                return ResourceManager.GetString("arabicḪāKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāKasraSukuun {
            get {
                return ResourceManager.GetString("arabicḪāKasraSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāKasraTanwin {
            get {
                return ResourceManager.GetString("arabicḤāKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḤāSukuum {
            get {
                return ResourceManager.GetString("arabicḤāSukuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string arabicḪāSukuun {
            get {
                return ResourceManager.GetString("arabicḪāSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٩ ähnelt.
        /// </summary>
        internal static string arabicNine {
            get {
                return ResourceManager.GetString("arabicNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ١ ähnelt.
        /// </summary>
        internal static string arabicOne {
            get {
                return ResourceManager.GetString("arabicOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٧ ähnelt.
        /// </summary>
        internal static string arabicSeven {
            get {
                return ResourceManager.GetString("arabicSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٦ ähnelt.
        /// </summary>
        internal static string arabicSix {
            get {
                return ResourceManager.GetString("arabicSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ت ähnelt.
        /// </summary>
        internal static string arabicTa {
            get {
                return ResourceManager.GetString("arabicTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تُ ähnelt.
        /// </summary>
        internal static string arabicTaDamma {
            get {
                return ResourceManager.GetString("arabicTaDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تٌ ähnelt.
        /// </summary>
        internal static string arabicTaDammaTanwin {
            get {
                return ResourceManager.GetString("arabicTaDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تَ ähnelt.
        /// </summary>
        internal static string arabicTaFatha {
            get {
                return ResourceManager.GetString("arabicTaFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تً ähnelt.
        /// </summary>
        internal static string arabicTaFathaTanwin {
            get {
                return ResourceManager.GetString("arabicTaFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تِ ähnelt.
        /// </summary>
        internal static string arabicTaKasra {
            get {
                return ResourceManager.GetString("arabicTaKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تٍ ähnelt.
        /// </summary>
        internal static string arabicTaKasraTanwin {
            get {
                return ResourceManager.GetString("arabicTaKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تْ ähnelt.
        /// </summary>
        internal static string arabicTaSukuun {
            get {
                return ResourceManager.GetString("arabicTaSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ث ähnelt.
        /// </summary>
        internal static string arabicTha {
            get {
                return ResourceManager.GetString("arabicTha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثُ ähnelt.
        /// </summary>
        internal static string arabicThaDamma {
            get {
                return ResourceManager.GetString("arabicThaDamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثٌ ähnelt.
        /// </summary>
        internal static string arabicThaDammaTanwin {
            get {
                return ResourceManager.GetString("arabicThaDammaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثَ ähnelt.
        /// </summary>
        internal static string arabicThaFatha {
            get {
                return ResourceManager.GetString("arabicThaFatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثً ähnelt.
        /// </summary>
        internal static string arabicThaFathaTanwin {
            get {
                return ResourceManager.GetString("arabicThaFathaTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثِ ähnelt.
        /// </summary>
        internal static string arabicThaKasra {
            get {
                return ResourceManager.GetString("arabicThaKasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثٍ ähnelt.
        /// </summary>
        internal static string arabicThaKasraTanwin {
            get {
                return ResourceManager.GetString("arabicThaKasraTanwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ثْ ähnelt.
        /// </summary>
        internal static string arabicThaSukuun {
            get {
                return ResourceManager.GetString("arabicThaSukuun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٣ ähnelt.
        /// </summary>
        internal static string arabicThree {
            get {
                return ResourceManager.GetString("arabicThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٢ ähnelt.
        /// </summary>
        internal static string arabicTwo {
            get {
                return ResourceManager.GetString("arabicTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ٠ ähnelt.
        /// </summary>
        internal static string arabicZero {
            get {
                return ResourceManager.GetString("arabicZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die    ähnelt.
        /// </summary>
        internal static string doubleSpace {
            get {
                return ResourceManager.GetString("doubleSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 8 ähnelt.
        /// </summary>
        internal static string latinEight {
            get {
                return ResourceManager.GetString("latinEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5 ähnelt.
        /// </summary>
        internal static string latinFive {
            get {
                return ResourceManager.GetString("latinFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4 ähnelt.
        /// </summary>
        internal static string latinFour {
            get {
                return ResourceManager.GetString("latinFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 9 ähnelt.
        /// </summary>
        internal static string latinNine {
            get {
                return ResourceManager.GetString("latinNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        internal static string latinOne {
            get {
                return ResourceManager.GetString("latinOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 7 ähnelt.
        /// </summary>
        internal static string latinSeven {
            get {
                return ResourceManager.GetString("latinSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 6 ähnelt.
        /// </summary>
        internal static string latinSix {
            get {
                return ResourceManager.GetString("latinSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 ähnelt.
        /// </summary>
        internal static string latinThree {
            get {
                return ResourceManager.GetString("latinThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 ähnelt.
        /// </summary>
        internal static string latinTwo {
            get {
                return ResourceManager.GetString("latinTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        internal static string latinZero {
            get {
                return ResourceManager.GetString("latinZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   ähnelt.
        /// </summary>
        internal static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
    }
}
